-- MySQL Script generated by MySQL Workbench
-- Wed Jun 11 10:08:13 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Region`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Region` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Region` (
  `reg_code` VARCHAR(20) NOT NULL,
  `reg_nom` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`reg_code`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Departement`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Departement` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Departement` (
  `dep_code` VARCHAR(10) NOT NULL,
  `dep_nom` VARCHAR(100) NOT NULL,
  `Region_reg_code` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`dep_code`),
  INDEX `fk_Departement_Region1_idx` (`Region_reg_code` ASC) VISIBLE,
  CONSTRAINT `fk_Departement_Region1`
    FOREIGN KEY (`Region_reg_code`)
    REFERENCES `mydb`.`Region` (`reg_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Commune`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Commune` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Commune` (
  `Cod_dep_Cod_com` VARCHAR(20) NOT NULL,
  `Com` VARCHAR(100) NOT NULL,
  `PTOT` INT NOT NULL,
  `Departement_dep_code` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`Cod_dep_Cod_com`),
  INDEX `fk_Commune_Departement1_idx` (`Departement_dep_code` ASC) VISIBLE,
  CONSTRAINT `fk_Commune_Departement1`
    FOREIGN KEY (`Departement_dep_code`)
    REFERENCES `mydb`.`Departement` (`dep_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Bien`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Bien` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Bien` (
  `id_Bien` VARCHAR(30) NOT NULL,
  `No_voie` VARCHAR(10) NOT NULL,
  `Type_voie` VARCHAR(10) NULL,
  `Voie` VARCHAR(50) NOT NULL,
  `Type_local` VARCHAR(50) NOT NULL,
  `Surface_reelle_bati` FLOAT NOT NULL,
  `Nombre_piece_principale` INT NOT NULL,
  `Surface_carrez` FLOAT NULL,
  `BTQ` VARCHAR(10) NULL,
  `Commune_Cod_dep_Cod_com` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_Bien`),
  INDEX `fk_Bien_Commune1_idx` (`Commune_Cod_dep_Cod_com` ASC) VISIBLE,
  CONSTRAINT `fk_Bien_Commune1`
    FOREIGN KEY (`Commune_Cod_dep_Cod_com`)
    REFERENCES `mydb`.`Commune` (`Cod_dep_Cod_com`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Vente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Vente` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Vente` (
  `id_Vente` VARCHAR(30) NOT NULL,
  `No_disposition` VARCHAR(45) NOT NULL,
  `Date_mutation` DATE NOT NULL,
  `Nature_mutation` VARCHAR(30) NOT NULL,
  `Valeur_fonciere` FLOAT NULL,
  `Bien_id_Bien` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id_Vente`),
  INDEX `fk_Vente_Bien1_idx` (`Bien_id_Bien` ASC) VISIBLE,
  CONSTRAINT `fk_Vente_Bien1`
    FOREIGN KEY (`Bien_id_Bien`)
    REFERENCES `mydb`.`Bien` (`id_Bien`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
